[package]
name = "zipr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.35"
clap = "4.5.2"
glob = "0.3.1"
zip = "0.6.6"

[dev-dependencies]
assert_cmd = "2.0.13"